/* It had generated by DirectStruct v1.6.1 */
#include "IDL_access_token.dsc.h"

#ifndef FUNCNAME_DSCLOG_access_token
#define FUNCNAME_DSCLOG_access_token	DSCLOG_access_token
#endif

#ifndef PREFIX_DSCLOG_access_token
#define PREFIX_DSCLOG_access_token	printf( 
#endif

#ifndef NEWLINE_DSCLOG_access_token
#define NEWLINE_DSCLOG_access_token	"\n"
#endif

int FUNCNAME_DSCLOG_access_token( access_token *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_access_token "access_token.access_token[%s]" NEWLINE_DSCLOG_access_token , pst->access_token );
	PREFIX_DSCLOG_access_token "access_token.expires_in[%d]" NEWLINE_DSCLOG_access_token , pst->expires_in );
	return 0;
}
