/* It had generated by DirectStruct v1.6.1 */
#include "IDL_xml_MsgType.dsc.h"

int DSCINIT_xml_MsgType( xml_MsgType *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(xml_MsgType) );
	return 0;
}

#include "fasterxml.h"

int DSCSERIALIZE_XML_xml_MsgType( xml_MsgType *pst , char *encoding , char *buf , int *p_len )
{
	int	remain_len ;
	int	len ;
	char	tabs[10+1] ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	remain_len = (*p_len) ;
	memset( tabs , '\t' , 10 );
	len=SNPRINTF(buf,remain_len,"<?xml version=\"1.0\" encoding=\"%s\"?>\n",encoding); if(len<0)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"<xml_MsgType>\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	<xml>\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"		<MsgType>"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%s",pst->xml.MsgType); XMLESCAPE_EXPAND(buf,len,remain_len); if(len<0||remain_len<len)return -1;
	len=SNPRINTF(buf,remain_len,"</MsgType>\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	</xml>\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"</xml_MsgType>\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	
	(*p_len) = (*p_len) - remain_len ;
	
	return 0;
}

funcCallbackOnXmlNode CallbackOnXmlNode_xml_MsgType ;
int CallbackOnXmlNode_xml_MsgType( int type , char *xpath , int xpath_len , int xpath_size , char *node , int node_len , char *properties , int properties_len , char *content , int content_len , void *p )
{
	xml_MsgType	*pst = (xml_MsgType*)p ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	
	if( type & FASTERXML_NODE_BRANCH )
	{
		if( type & FASTERXML_NODE_ENTER )
		{
		}
		else if( type & FASTERXML_NODE_LEAVE )
		{
		}
	}
	else if( type & FASTERXML_NODE_LEAF )
	{
			/* MsgType */
			if( xpath_len == 24 && strncmp( xpath , "/xml_MsgType/xml/MsgType" , xpath_len ) == 0 )
			{XMLUNESCAPE_FOLD(content,content_len,pst->xml.MsgType);
			{if( content_len > sizeof(pst->xml.MsgType)-1 ) return -7;}}
	}
	
	return 0;
}

int DSCDESERIALIZE_XML_xml_MsgType( char *encoding , char *buf , int *p_len , xml_MsgType *pst )
{
	char	xpath[ 1024 + 1 ] ;
	int	nret = 0 ;
	memset( xpath , 0x00 , sizeof(xpath) );
	nret = TravelXmlBuffer( buf , xpath , sizeof(xpath) , & CallbackOnXmlNode_xml_MsgType , (void*)pst ) ;
	if( nret )
		return nret;
	
	return 0;
}
