/* It had generated by DirectStruct v1.6.1 */
#include "IDL_xml_MsgType.dsc.h"

#ifndef FUNCNAME_DSCLOG_xml_MsgType
#define FUNCNAME_DSCLOG_xml_MsgType	DSCLOG_xml_MsgType
#endif

#ifndef PREFIX_DSCLOG_xml_MsgType
#define PREFIX_DSCLOG_xml_MsgType	printf( 
#endif

#ifndef NEWLINE_DSCLOG_xml_MsgType
#define NEWLINE_DSCLOG_xml_MsgType	"\n"
#endif

int FUNCNAME_DSCLOG_xml_MsgType( xml_MsgType *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
		PREFIX_DSCLOG_xml_MsgType "xml_MsgType.xml.MsgType[%s]" NEWLINE_DSCLOG_xml_MsgType , pst->xml.MsgType );
	return 0;
}
