/* It had generated by DirectStruct v1.6.1 */
#include "IDL_xml.dsc.h"

#ifndef FUNCNAME_DSCLOG_xml
#define FUNCNAME_DSCLOG_xml	DSCLOG_xml
#endif

#ifndef PREFIX_DSCLOG_xml
#define PREFIX_DSCLOG_xml	printf( 
#endif

#ifndef NEWLINE_DSCLOG_xml
#define NEWLINE_DSCLOG_xml	"\n"
#endif

int FUNCNAME_DSCLOG_xml( xml *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_xml "xml.ToUserName[%s]" NEWLINE_DSCLOG_xml , pst->ToUserName );
	PREFIX_DSCLOG_xml "xml.FromUserName[%s]" NEWLINE_DSCLOG_xml , pst->FromUserName );
	PREFIX_DSCLOG_xml "xml.CreateTime[%s]" NEWLINE_DSCLOG_xml , pst->CreateTime );
	PREFIX_DSCLOG_xml "xml.MsgType[%s]" NEWLINE_DSCLOG_xml , pst->MsgType );
	PREFIX_DSCLOG_xml "xml.Content[%s]" NEWLINE_DSCLOG_xml , pst->Content );
	PREFIX_DSCLOG_xml "xml.MsgId[%s]" NEWLINE_DSCLOG_xml , pst->MsgId );
	return 0;
}
